FROM node:18.12.1 as build
WORKDIR /app
COPY . ./

RUN git submodule update --init --recursive


RUN npm install
RUN npm run build

# production env
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
